# Generated by Django 4.2.7 on 2024-11-03 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', 'XXXX_add_region_med_centers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regionmedcenter',
            name='med_center',
            field=models.CharField(choices=[('ТОО «Медикер Астана»', 'ТОО «Медикер Астана»'), ('ТОО «Медикер Педиатрия»', 'ТОО «Медикер Педиатрия»'), ('ТОО «Медикер Илек»', 'ТОО «Медикер Илек»'), ('ТОО «Алатау Ассистанс»', 'ТОО «Алатау Ассистанс»'), ('ТОО «Qamqor Clinic Almaty»', 'ТОО «Qamqor Clinic Almaty»'), ('ТОО «MIH»', 'ТОО «MIH»'), ('ТОО «Медикер Жайык»', 'ТОО «Медикер Жайык»'), ('ТОО «Медикер Аксай»', 'ТОО «Медикер Аксай»'), ('ТОО «Медикер ЮК»', 'ТОО «Медикер ЮК»'), ('ТОО «МЦ Онидрис»', 'ТОО «МЦ Онидрис»'), ('ТОО «Медикер Каспий»', 'ТОО «Медикер Каспий»'), ('ТОО «Uzenmedics»', 'ТОО «Uzenmedics»'), ('ТОО «Медикер Ертис»', 'ТОО «Медикер Ертис»'), ('ТОО «Мейирим»', 'ТОО «Мейирим»')], max_length=50),
        ),
        migrations.AlterField(
            model_name='regionmedcenter',
            name='region',
            field=models.CharField(choices=[('', 'Не указано'), ('ASTANA', 'Астана'), ('ALMATY', 'Алматы'), ('AKTOBE', 'Актюбинская область'), ('ATYRAUSKAYA', 'Атырауская область'), ('ZAPADNO', 'Западно-Казахстанская область'), ('KYZYLORDA', 'Кызылординская область'), ('MANGISTAU', 'Мангистауская область'), ('PAVLODAR', 'Павлодарская область'), ('TURKESTAN', 'Южно-Казахстанская область')], max_length=50),
        ),
        migrations.AlterField(
            model_name='usercity',
            name='city',
            field=models.CharField(blank=True, choices=[('', 'Не указано'), ('ASTANA', 'Астана'), ('ALMATY', 'Алматы'), ('AKTOBE', 'Актюбинская область'), ('ATYRAUSKAYA', 'Атырауская область'), ('ZAPADNO', 'Западно-Казахстанская область'), ('KYZYLORDA', 'Кызылординская область'), ('MANGISTAU', 'Мангистауская область'), ('PAVLODAR', 'Павлодарская область'), ('TURKESTAN', 'Южно-Казахстанская область')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usermed',
            name='med_center',
            field=models.CharField(blank=True, choices=[('ТОО «Медикер Астана»', 'ТОО «Медикер Астана»'), ('ТОО «Медикер Педиатрия»', 'ТОО «Медикер Педиатрия»'), ('ТОО «Медикер Илек»', 'ТОО «Медикер Илек»'), ('ТОО «Алатау Ассистанс»', 'ТОО «Алатау Ассистанс»'), ('ТОО «Qamqor Clinic Almaty»', 'ТОО «Qamqor Clinic Almaty»'), ('ТОО «MIH»', 'ТОО «MIH»'), ('ТОО «Медикер Жайык»', 'ТОО «Медикер Жайык»'), ('ТОО «Медикер Аксай»', 'ТОО «Медикер Аксай»'), ('ТОО «Медикер ЮК»', 'ТОО «Медикер ЮК»'), ('ТОО «МЦ Онидрис»', 'ТОО «МЦ Онидрис»'), ('ТОО «Медикер Каспий»', 'ТОО «Медикер Каспий»'), ('ТОО «Uzenmedics»', 'ТОО «Uzenmedics»'), ('ТОО «Медикер Ертис»', 'ТОО «Медикер Ертис»'), ('ТОО «Мейирим»', 'ТОО «Мейирим»')], max_length=50, null=True),
        ),
    ]
