# Generated by Django 4.2.7 on 2024-06-19 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_userdesc_remove_user_city_alter_user_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='choices',
            name='scores',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
