# Generated by Django 4.2.7 on 2024-06-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_choices_scores'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='max_value',
            field=models.IntegerField(default=100),
        ),
    ]
