# Generated by Django 4.2.7 on 2024-06-26 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_questions_max_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='max_value',
        ),
    ]
