# Generated by Django 4.2.7 on 2024-11-12 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_alter_regionmedcenter_region_alter_usercity_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questions',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='questions',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
