# Generated by Django 4.2.7 on 2024-11-12 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_alter_questions_options_questions_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='confirmation_message',
            field=models.CharField(default='Ва�� ответ был отправлен.', max_length=10000),
        ),
        migrations.AlterField(
            model_name='questions',
            name='max_value',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
