# Generated by Django 4.2.7 on 2024-11-12 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_alter_form_confirmation_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='confirmation_message',
            field=models.CharField(default='Ваш ответ был отправлен.', max_length=10000),
        ),
    ]
