# Generated by Django 4.2.7 on 2024-06-30 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_questions_max_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='is_list',
            field=models.BooleanField(default=False),
        ),
    ]
