# Generated by Django 4.2.7 on 2024-11-12 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_alter_form_confirmation_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
