# Generated by Django 4.2.7 on 2024-06-30 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_questions_is_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, choices=[('', 'Выбрать страну'), ('Алматы', 'Алматы'), ('Астана', 'Астана'), ('Караганда', 'Караганда'), ('Шымкент', 'Шымкент'), ('Актобе', 'Актобе'), ('Семей', 'Семей'), ('Атырау', 'Атырау'), ('Павлодар', 'Павлодар'), ('Уральск', 'Уральск'), ('Усть-Каменогорск', 'Усть-Каменогорск'), ('Кокшетау', 'Кокшетау'), ('Костанай', 'Костанай'), ('Петропавлск', 'Петропавловск'), ('Орал', 'Орал'), ('Талдыкорган', 'Талдыкорган')], max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='city_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_info', to='index.usercity'),
        ),
    ]
