# Generated by Django 4.2.7 on 2024-11-17 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_form_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='is_negative',
            field=models.BooleanField(default=False),
        ),
    ]
