# Generated by Django 4.2.7 on 2024-06-30 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_usercity_user_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='max_value',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
        migrations.AlterField(
            model_name='usercity',
            name='city',
            field=models.CharField(blank=True, choices=[('', 'Выбрать страну'), ('Не указано', 'Не указано'), ('Алматы', 'Алматы'), ('Астана', 'Астана'), ('Караганда', 'Караганда'), ('Шымкент', 'Шымкент'), ('Актобе', 'Актобе'), ('Семей', 'Семей'), ('Атырау', 'Атырау'), ('Павлодар', 'Павлодар'), ('Уральск', 'Уральск'), ('Усть-Каменогорск', 'Усть-Каменогорск'), ('Кокшетау', 'Кокшетау'), ('Костанай', 'Костанай'), ('Петропавлск', 'Петропавловск'), ('Орал', 'Орал'), ('Талдыкорган', 'Талдыкорган')], max_length=50, null=True),
        ),
    ]
