# Generated by Django 4.2.7 on 2024-11-26 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_questions_is_negative'),
    ]

    operations = [
        migrations.AddField(
            model_name='responses',
            name='responder_age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='responses',
            name='responder_birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='responses',
            name='responder_city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='responses',
            name='responder_gender',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
