# Generated by Django 4.2.7 on 2024-11-26 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_responses_responder_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='responses',
            name='responder_username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
