# Generated by Django 4.2.7 on 2024-11-26 23:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_responses_responder_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responses',
            name='createdAt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
