# Generated by Django 4.2.7 on 2024-11-29 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0013_alter_regionmedcenter_med_center_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regionmedcenter',
            name='med_center',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='usermed',
            name='med_center',
            field=models.CharField(max_length=50),
        ),
    ]
