# Generated by Django 4.2.7 on 2024-11-29 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0015_alter_usermed_med_center'),
        ('index', 'xxxx_allow_null_med_center'),
    ]

    operations = [
    ]
