# Generated by Django 4.2.7 on 2024-08-15 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0015_alter_answer_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avgvalue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=5000)),
                ('value_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='value_to', to='index.questions')),
            ],
        ),
    ]
