# Generated by Django 4.2.7 on 2025-05-06 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0016_merge_20241129_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('trainer', 'Тренер'), ('manager', 'Руководитель'), ('user', 'Пользователь')], default='user', max_length=20),
        ),
    ]
