# Generated by Django 4.2.7 on 2024-08-15 08:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0016_avgvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='avgvalue',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
