# Generated by Django 4.2.7 on 2024-08-15 09:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0018_responses_createdat_delete_avgvalue'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvgValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_value', models.FloatField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.questions')),
            ],
            options={
                'unique_together': {('question', 'date')},
            },
        ),
    ]
