# Generated by Django 4.2.7 on 2025-05-10 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0018_remove_user_role_userrole'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedCenterGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('centers', models.ManyToManyField(related_name='groups', to='index.regionmedcenter')),
            ],
            options={
                'verbose_name': 'Группа медцентров',
                'verbose_name_plural': 'Группы медцентров',
            },
        ),
    ]
