# Generated by Django 4.2.7 on 2024-08-15 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0019_avgvalue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responses',
            name='createdAt',
        ),
        migrations.DeleteModel(
            name='AvgValue',
        ),
    ]
