# Generated by Django 4.2.7 on 2025-05-10 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0019_medcentergroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medcentergroup',
            name='centers',
        ),
        migrations.AddField(
            model_name='regionmedcenter',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='centers', to='index.medcentergroup'),
        ),
        migrations.AlterField(
            model_name='medcentergroup',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
