# Generated by Django 4.2.7 on 2025-05-14 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0021_alter_medcentergroup_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='background_color',
            field=models.CharField(default='#0D0D11', max_length=20),
        ),
    ]
