# Generated by Django 4.2.7 on 2024-08-27 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0021_responses_createdat'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='limit_ip',
            field=models.BooleanField(default=False),
        ),
    ]
