# Generated by Django 4.2.7 on 2024-09-03 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0022_form_limit_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('med_center', models.CharField(blank=True, choices=[('ТОО «Медикер Астана»', 'ТОО «Медикер Астана»'), ('ТОО «Медикер Илек»', 'ТОО «Медикер Илек»'), ('ТОО «Медикер Жайык»', 'ТОО «Медикер Жайык»'), ('ТОО «Uzenmedics»', 'ТОО «Uzenmedics»'), ('ТОО «Медикер Ертис»', 'ТОО «Медикер Ертис»'), ('ТОО «Qamqor Clinic Almaty»', 'ТОО «Qamqor Clinic Almaty»'), ('ТОО «Медикер Каспий»', 'ТОО «Медикер Каспий»'), ('ТОО «МЦ Онидрис»', 'ТОО «МЦ Онидрис»'), ('ТОО «Медикер Педиатрия»', 'ТОО «Медикер Педиатрия»'), ('ТОО «MIH»', 'ТОО «MIH»'), ('ТОО «Мейирим»', 'ТОО «Мейирим»'), ('ТОО «Медикер ЮК»', 'ТОО «Медикер ЮК»'), ('ТОО «Медикер Аксай»', 'ТОО «Медикер Аксай»'), ('ТОО «Алатау Ассистанс»', 'ТОО «Алатау Ассистанс»')], max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='med_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='med_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_info', to='index.usermed'),
        ),
    ]
