# Generated by Django 4.2.7 on 2024-09-09 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0027_alter_responses_responder_med'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responses',
            name='responder_med',
        ),
    ]
