# Generated by Django 4.2.7 on 2024-09-09 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0030_alter_responses_responder_med'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responses',
            name='responder_med',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
