# Generated by Django 4.2.7 on 2024-09-17 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0031_alter_responses_responder_med'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='submit_limit',
            field=models.BooleanField(default=False),
        ),
    ]
