# Generated by Django 4.2.7 on 2024-09-22 22:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0032_form_submit_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dateofbirth',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='date_info', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usergender',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gender_info', to=settings.AUTH_USER_MODEL),
        ),
    ]
