# Generated by Django 4.2.7 on 2024-09-24 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0033_alter_dateofbirth_user_alter_usergender_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_skipped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questions',
            name='is_skip',
            field=models.BooleanField(default=False),
        ),
    ]
