# Generated by Django 4.2.7 on 2024-10-06 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0036_remove_singleform_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='singleform',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
