# Generated by Django 4.2.7 on 2024-10-06 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0037_singleform_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='is_single_form',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='SingleForm',
        ),
    ]
