# Generated by Django 4.2.7 on 2024-10-23 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0038_form_is_single_form_delete_singleform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_url',
        ),
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
